name: "format"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
        
    - name: Run format.sh
      run: cd "${GITHUB_WORKSPACE}" && ./format.sh

    - name: Check formatting diff
      run: |
        CHANGED_FILES="$(cd "${GITHUB_WORKSPACE}" && git diff-index --name-only HEAD --)"
        if [[ -z "${CHANGED_FILES}" ]]; then
          echo "Success: no formatting changes needed."
          exit 0
        fi
        echo "Found formatting changes in the following files:"
        echo "${CHANGED_FILES}"
        echo ""
        echo "Please run format.sh to apply the changes."
        exit 1
