name: "gold test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/checkout@v2
      with:
        repository: EileenFeng/p4c
        path: p4c
        submodules: recursive
    
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.cache/bazel"  # See https://docs.bazel.build/versions/master/output_directories.html
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
        
    - name: Build p4_constraints
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //p4_constraints/...
        
    - name: Build p4c
      run: |
        cd "${GITHUB_WORKSPACE}/p4c"
        sudo apt-get install bison flex libgmp-dev libboost-dev libboost-iostreams-dev libboost-graph-dev
        "${GITHUB_WORKSPACE}/bin/bazel" build //:p4c_bmv2
        sudo ln -s "$(realpath "${GITHUB_WORKSPACE}/p4c/bazel-bin/p4c_bmv2")" /bin/p4c
        
    - name: Gold test
      run: |
        cd "${GITHUB_WORKSPACE}"
        "${GITHUB_WORKSPACE}/bin/bazel" test //test/... --test_output=errors
