name: gold test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      MAKEFLAGS: '-j32'
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install protobuf
      run: |
        cd third_party/protobuf
        ./autogen.sh
        ./configure
        make -j32
        sudo make install
        sudo ldconfig

    - name: Install p4c
      run: |
        cd third_party/p4c
        chmod +x tools/travis-build
        sudo ./tools/travis-build
        
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64"
        mv bazelisk-linux-amd64 bazel
        chmod +x bazel
        
    - name: Build p4-constraints
      run: bazel build //test/...
    
    - name: Run gold tests
      run: bazel test //test/... --test_output=errors
