name: experiment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: p4lang/p4c
        submodules: recursive

    - uses: actions/checkout@v2
      with:
        repository: protocolbuffers/protobuf
        submodules: recursive
        path: protobuf
        ref: '3.12.x'

    - name: Install protobuf
      run: |
        cd protobuf
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

    - name: Build p4c
      run: |
        chmod +x tools/travis-build
        sudo ./tools/travis-build
