name: experiment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: p4lang/p4c
        submodules: recursive

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        chmod +x tools/travis-build
        sudo ./tools/travis-build
